[build-system]
build-backend = "cmeel.build"
requires = [
  "cmeel-boost[build] ~= 1.90.0",
  "cmeel-tinyxml2[build]",
  "cmeel[build]",
  "jrl-cmakemodules"
]

[project]
dependencies = [
  "cmeel-boost ~= 1.90.0",
  "cmeel-tinyxml2"
]
description = "Debugging tools for the HPP project."
license = "BSD-2-Clause"
name = "hpp-util"
version = "9.0.0"

[tool.cmeel]
has-sitelib = false

[tool.ruff]
extend-exclude = ["cmake"]

[tool.ruff.lint]
extend-select = ["I", "NPY", "RUF", "UP", "W"]

[tool.tomlsort]
all = true
